name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # 觸發條件：v1.0.0 這種 tag

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build binary
        run: |
          mkdir -p dist
          output_name="go-cat-${{ matrix.goos }}-${{ matrix.goarch }}"
          if [ "${{ matrix.goos }}" == "windows" ]; then
            output_name="${output_name}.exe"
          fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/${output_name}

      - name: Archive binary
        run: |
          cd dist
          if [ "${{ matrix.goos }}" == "windows" ]; then
            zip ${output_name}.zip ${output_name}
            rm ${output_name}
          else
            tar -czvf ${output_name}.tar.gz ${output_name}
            rm ${output_name}
          fi

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*