name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Get short commit hash
        id: vars
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build binary
        run: |
          mkdir -p dist
          output_name="go-cat-${{ matrix.goos }}-${{ matrix.goarch }}-${{ steps.vars.outputs.hash }}"
          if [ "${{ matrix.goos }}" == "windows" ]; then
            output_name="${output_name}.exe"
          fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/${output_name} ./cmd

      - name: Archive binary
        run: |
          cd dist
          if [ "${{ matrix.goos }}" == "windows" ]; then
            zip ${output_name}.zip ${output_name}
            rm ${output_name}
          else
            tar -czvf ${output_name}.tar.gz ${output_name}
            rm ${output_name}
          fi

      - name: Generate changelog
        id: changelog
        run: |
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          git log -1 --pretty=format:"%h - %s (%an)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          body: |
            ${{ steps.changelog.outputs.changelog }}